version: "3.2"
services:
  nodejs:
    container_name: test-nodejs-app
    restart: always
    depends_on: 
      -mysql
    build: .
    ports:
      - '80:3000'
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment: 
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=123
      - MYSQL_DB=users
    ports:
      - '30001:8005'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: test-mysql-phpmyadmin
    depends_on: 
      - mysql
    environment: 
      - PMA_HOST=mysql
      - PMA_POST=3306
    ports:
      - 30002:80
    links:
      - mysql
    